import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer"; // <-- import Footer
import ScrollingTicker from './components/Marquee';
import RouteChangeLoader from "./RouteChangeLoader";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Aid 4 Children Tanzania",
  description: "Generated by Little",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RouteChangeLoader />
        <Navbar />
        
        <ScrollingTicker />
        
        <main className="min-h-screen">{children}</main>
        
        <Footer /> 
      </body>
    </html>
  );
}
